#include "filenamelist.h"

const char* roadmapdata[] = {
    PLATFORMPATH"/mapdata/china/maps/CN00R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN01R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN02R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN03R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN04R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN05R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN06R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN07R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN08R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN09R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN10R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN11R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN12R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN13R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN14R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN15R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN16R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN17R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN18R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN19R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN20R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN21R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN22R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN23R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN24R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN25R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN26R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN27R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN28R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN29R0WM.map",
    PLATFORMPATH"/mapdata/china/maps/CN30R0WM.map"
};

const char* poimapdata[] = {
    PLATFORMPATH"/mapdata/china/pois/CN00ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN01ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN02ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN03ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN04ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN05ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN06ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN07ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN08ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN09ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN10ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN11ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN12ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN13ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN14ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN15ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN16ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN17ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN18ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN19ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN20ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN21ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN22ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN23ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN24ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN25ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN26ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN27ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN28ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN29ICWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN30ICWM.map",

    PLATFORMPATH"/mapdata/china/pois/CN00IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN01IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN02IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN03IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN04IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN05IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN06IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN07IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN08IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN09IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN10IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN11IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN12IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN13IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN14IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN15IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN16IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN17IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN18IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN19IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN20IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN21IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN22IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN23IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN24IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN25IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN26IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN27IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN28IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN29IGWM.map",
    PLATFORMPATH"/mapdata/china/pois/CN30IGWM.map"
};

const char* poitypemapdata[] = {
    PLATFORMPATH"/mapdata/china/poitype/0000T032.map"
};


const char* polymapdata[] = {
    PLATFORMPATH"/mapdata/china/polys/0000PB18.map",

    PLATFORMPATH"/mapdata/china/polys/CN00P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN01P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN02P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN03P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN04P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN05P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN06P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN07P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN08P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN09P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN10P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN11P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN12P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN13P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN14P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN15P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN16P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN17P0WN.map",
    PLATFORMPATH"/mapdata/china/polys/CN18P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN19P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN20P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN21P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN22P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN23P0WM.map",
    PLATFORMPATH"/mapdata/china/polys/CN24P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN25P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN26P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN27P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN28P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN29P0WP.map",
    PLATFORMPATH"/mapdata/china/polys/CN30P0WP.map"

};



bool initfilelist()
{
    return true;
}
