#ifndef _READCOM_PROTOCOL_H_
#define _READCOM_PROTOCOL_H_

#include "serialbase.h"

#define ACQUISITION_VERSION_NUMBER			0x00

#define ACQUISITION_DRIVER_INFOMATION		0x01
#define ACQUISITION_REAL_TIME				0x02
#define ACQUISITION_360H_TOTAL_MILEAGE		0x03
#define ACQUISITION_SPEEDPULSE_COEFFICIENT	0x04
#define ACQUISITION_360H_SPEEDDATA			0x05
#define ACQUISITION_VEHICLE_INFOMATION		0x06
#define ACQUISITION_ACCIDENT_POINTS			0x07
#define ACQUISITION_TWODAY_TOTAL_MILEAGE	0x08
#define ACQUISITION_TWODAY_SPEEDDATA		0x09
#define ACQUISITION_FATIGUE_DRIVING			0x11	


#define SETUP_DRIVER_INFOMATION				0x81
#define SETUP_VEHICLE_INFOMATION			0x82
#define SETUP_REAL_TIME						0xC2
#define SETUP_SPEEDPULSE_COEFFICIENT		0xC3


#define UPLOAD_RESPONSE_FRAME_SIGN			0xFA
#define DOWNLOAD_RESPONSE_FRAME_SIGN		0xFB


#define MAX_LEN    1024

void serial_protocol_init();
int  check_sum(unsigned char *buf,int len);


#endif
