// This file contains the property definitions for the Si47xx Parts.
#ifndef _PROPERTY_DEFS_H_
#define _PROPERTY_DEFS_H_

// General Properties
#define INT_CTL_ENABLE                        0x0000
#define CLOCK_RCLK_FREQ                       0x0100
#define DIGITAL_IO_INPUT_SAMPLE_RATE          0x0200
#define DIGITAL_IO_INPUT_FORMAT               0x0201
#define DIGITAL_IO_OUTPUT_SAMPLE_RATE         0x0202
#define DIGITAL_IO_OUTPUT_FORMAT              0x0203
#define AUDIO_ANALOG_VOLUME                   0x0300
#define AUDIO_MUTE                            0x0301
#define AUDIO_DIV_MIX                         0x0303
#define SOFT_MUTE_MAX_ATTENUATION             0x0400
#define SOFT_MUTE_TRIGGER_THRESHOLD           0x0401
#define SOFT_MUTE_END_THRESHOLD               0x0402
#define SOFT_MUTE_RELEASE_TIME                0x0403
#define SOFT_MUTE_ATTACK_TIME                 0x0404
#define ZIF_OUTPUT_CFG                        0x0600

// AM Receive Properties
#define AUDIO_PWR_LINE_FILTER                 0x0304
#define AM_AVC_MIN_GAIN                       0x0500
#define AM_AVC_MAX_GAIN                       0x0501
#define AM_AGC_FE_CONFIG                      0x0700
#define AM_AGC_PD_CONFIG                      0x0701
#define AM_AGC_FW_LNA_PD_AGC_ATTACK_MS        0x0702
#define AM_AGC_FW_LNA_PD_AGC_RELEASE_MS       0x0703
#define AM_AGC_FW_LNA_PD_THRESHOLD            0x0704
#define AM_AGC_FM_MIXER_PD_AGC_ATTACK_MS      0x0705
#define AM_AGC_FM_MIXER_PD_AGC_RELEASE_MS     0x0706
#define AM_AGC_FM_MIXER_PD_THRESHOLD          0x0707
#define AM_AGC_AM_LNA_PD_AGC_ATTACK_MS        0x070C
#define AM_AGC_AM_LNA_PD_AGC_RELEASE_MS       0x070D
#define AM_AGC_AM_LNA_PD_THRESHOLD            0x070E
#define AM_AGC_OVERRIDE                       0x0710
#define AM_AGC_FMATTEN1                       0x0711
#define AM_AGC_FMATTEN2                       0x0712
#define AM_AGC_LNA_GAIN                       0x0713
#define AM_AGC_PGA_GAIN                       0x0714
#define AM_AGC_WHIP_CAP_ATTEN                 0x0715
#define AM_AGC_WHIP_RES_ATTEN                 0x0716
#define AM_SEEK_BAND_BOTTOM                   0x1100
#define AM_SEEK_BAND_TOP                      0x1101
#define AM_SEEK_FREQUENCY_SPACING             0x1102
#define AM_RSQ_INTERRUPT_SOURCE               0x1200
#define AM_RSQ_SNR_HIGH_THRESHOLD             0x1201
#define AM_RSQ_SNR_LOW_THRESHOLD              0x1202
#define AM_RSQ_RSSI_HIGH_THRESHOLD            0x1203
#define AM_RSQ_RSSI_LOW_THRESHOLD             0x1204
#define AM_RSQ_ISSI_HIGH_THRESHOLD            0x1205
#define AM_RSQ_ISSI_LOW_THRESHOLD             0x1206
#define AM_ACF_INTERRUPT_SOURCE               0x1300
#define AM_ACF_SM_THRESHOLD                   0x1301
#define AM_ACF_CBW_THRESHOLD                  0x1302
#define AM_ACF_HC_THRESHOLD                   0x1303
#define AM_ACF_CONTROL_SOURCE                 0x1306
#define AM_VALID_MAX_TUNE_ERROR               0x2000
#define AM_VALID_RSSI_TIME                    0x2001
#define AM_VALID_SNR_TIME                     0x2002
#define AM_VALID_SNR_THRESHOLD                0x2003
#define AM_VALID_RSSI_THRESHOLD               0x2004
#define AM_VALID_ISSI_THRESHOLD               0x2005
#define AM_NB_DETECT_THRESHOLD                0x2100
#define AM_NB_INTERVAL                        0x2101
#define AM_SECONDARY_NB_DETECT_THRESHOLD                        0x2103
#define AM_SECONDARY_NB_INTERVAL                        0x2104
#define AM_NB_SCHEME							  0x2108
#define AM_NB_MODE_CONTROL			  0x2109
#define AM_CHBW_SNR_MIN_MAX                   0x2200
#define AM_CHBW_SNR_HIGH_THRESHOLD            0x2201
#define AM_CHBW_SNR_LOW_THRESHOLD             0x2202
#define AM_CHBW_SNR_WIDENING_TIME             0x2203
#define AM_CHBW_SNR_NARROWING_TIME            0x2204
#define AM_HICUT_SNR_HIGH_THRESHOLD           0x3100
#define AM_HICUT_SNR_LOW_THRESHOLD            0x3101
#define AM_HICUT_ATTACK_TIME                  0x3106
#define AM_HICUT_RELEASE_TIME                 0x3107
#define AM_HICUT_CUTOFF_FREQ                  0x3108
#define AM_IBOC_CONTROL                       0x3300
#define AM_IBOC_ANALOG_TO_HD_CROSSFADE_TIME   0x3301
#define AM_IBOC_HD_TO_ANALOG_CROSSFADE_TIME   0x3302
#define AM_IBOC_DYNAMIC_GAIN                  0x3303
#define AM_IBOC_STATIC_GAIN                   0x3304

// FM Receive Properties
#define AUDIO_DE_EMPHASIS                     0x0302
#define FM_AGC_FE_CONFIG                      0x0700
#define FM_AGC_PD_CONFIG                      0x0701
#define FM_AGC_FW_LNA_PD_AGC_ATTACK_MS        0x0702
#define FM_AGC_FW_LNA_PD_AGC_RELEASE_MS       0x0703
#define FM_AGC_FW_LNA_PD_THRESHOLD            0x0704
#define FM_AGC_FM_MIXER_PD_AGC_ATTACK_MS      0x0705
#define FM_AGC_FM_MIXER_PD_AGC_RELEASE_MS     0x0706
#define FM_AGC_FM_MIXER_PD_THRESHOLD          0x0707
#define FM_AGC_AM_LNA_PD_AGC_ATTACK_MS        0x070C
#define FM_AGC_AM_LNA_PD_AGC_RELEASE_MS       0x070D
#define FM_AGC_AM_LNA_PD_THRESHOLD            0x070E
#define FM_AGC_OVERRIDE                       0x0710
#define FM_AGC_FMATTEN1                       0x0711
#define FM_AGC_FMATTEN2                       0x0712
#define FM_AGC_LNA_GAIN                       0x0713
#define FM_AGC_PGA_GAIN                       0x0714
#define FM_AGC_WHIP_CAP_ATTEN                 0x0715
#define FM_AGC_WHIP_RES_ATTEN                 0x0716
#define FM_SEEK_BAND_BOTTOM                   0x1100
#define FM_SEEK_BAND_TOP                      0x1101
#define FM_SEEK_FREQUENCY_SPACING             0x1102
#define FM_RSQ_INTERRUPT_SOURCE               0x1200
#define FM_RSQ_SNR_HIGH_THRESHOLD             0x1201
#define FM_RSQ_SNR_LOW_THRESHOLD              0x1202
#define FM_RSQ_RSSI_HIGH_THRESHOLD            0x1203
#define FM_RSQ_RSSI_LOW_THRESHOLD             0x1204
#define FM_RSQ_ISSI_HIGH_THRESHOLD            0x1205
#define FM_RSQ_ISSI_LOW_THRESHOLD             0x1206
#define FM_RSQ_MULTIPATH_HIGH_THRESHOLD       0x1207
#define FM_RSQ_MULTIPATH_LOW_THRESHOLD        0x1208
#define FM_ACF_INTERRUPT_SOURCE               0x1300
#define FM_ACF_SM_THRESHOLD                   0x1301
#define FM_ACF_CBW_THRESHOLD                  0x1302
#define FM_ACF_HC_LPR_THRESHOLD               0x1303
#define FM_ACF_HC_LMR_THRESHOLD               0x1304
#define FM_ACF_BLEND_THRESHOLD                0x1305
#define FM_ACF_CONTROL_SOURCE                 0x1306
#define FM_VALID_MAX_TUNE_ERROR               0x2000
#define FM_VALID_RSSI_TIME                    0x2001
#define FM_VALID_SNR_TIME                     0x2002
#define FM_VALID_SNR_THRESHOLD                0x2003
#define FM_VALID_RSSI_THRESHOLD               0x2004
#define FM_VALID_ISSI_THRESHOLD               0x2005
#define FM_NB_DETECT_THRESHOLD                0x2100
#define FM_NB_INTERVAL                        0x2101
#define FM_CHBW_DEV_MIN_MAX                   0x2200
#define FM_CHBW_DEV_HIGH_THRESHOLD            0x2201
#define FM_CHBW_DEV_LOW_THRESHOLD             0x2202
#define FM_CHBW_DEV_WIDENING_TIME             0x2203
#define FM_CHBW_DEV_NARROWING_TIME            0x2204
#define FM_CHBW_ASSI_MIN_MAX                  0x2205
#define FM_CHBW_ASSI_LOW_THRESHOLD            0x2206
#define FM_CHBW_ASSI_HIGH_THRESHOLD           0x2207
#define FM_CHBW_ASSI_WIDENING_TIME            0x2208
#define FM_CHBW_ASSI_NARROWING_TIME           0x2209
#define FM_BLEND_SNR_STEREO_THRESHOLD         0x3000
#define FM_BLEND_SNR_ATTACK_TIME              0x3002
#define FM_BLEND_SNR_RELEASE_TIME             0x3003
#define FM_BLEND_MULTIPATH_STEREO_THRESHOLD   0x3004
#define FM_BLEND_MULTIPATH_MONO_THRESHOLD     0x3005
#define FM_BLEND_MULTIPATH_ATTACK_TIME        0x3006
#define FM_BLEND_MULTIPATH_RELEASE_TIME       0x3007
#define FM_BLEND_STEREO_SEPARATION            0x3008
#define FM_HICUT_SNR_LPR_HIGH_THRESHOLD       0x3100
#define FM_HICUT_SNR_LPR_LOW_THRESHOLD        0x3101
#define FM_HICUT_SNR_LMR_HIGH_THRESHOLD       0x3102
#define FM_HICUT_SNR_LMR_LOW_THRESHOLD        0x3103
#define FM_HICUT_MULTIPATH_LMR_HIGH_THRESHOLD 0x3104
#define FM_HICUT_MULTIPATH_LMR_LOW_THRESHOLD  0x3105
#define FM_HICUT_ATTACK_TIME                  0x3106
#define FM_HICUT_RELEASE_TIME                 0x3107
#define FM_HICUT_LPR_CUTOFF_FREQ              0x3108
#define FM_HICUT_LMR_CUTOFF_FREQ              0x3109
#define FM_IBOC_CONTROL                       0x3300
#define FM_IBOC_ANALOG_TO_HD_CROSSFADE_TIME   0x3301
#define FM_IBOC_HD_TO_ANALOG_CROSSFADE_TIME   0x3302
#define FM_IBOC_DYNAMIC_GAIN                  0x3303
#define FM_IBOC_STATIC_GAIN                   0x3304
#define FM_CAL_CAPACITOR					  0x8000
#define FM_CAL_FMAX							  0x8001

// FM RDS Receive Properties
#define FM_RDS_INTERRUPT_SOURCE               0x4000
#define FM_RDS_INTERRUPT_FIFO_COUNT           0x4001
#define FM_RDS_CONFIG                         0x4002
#define FM_RDS_CONFIDENCE                     0x4003

// WB Receive Properties
#define WB_AVC_MIN_GAIN                       0x0500
#define WB_AVC_MAX_GAIN                       0x0501
#define WB_AGC_FE_CONFIG                      0x0700
#define WB_AGC_PD_CONFIG                      0x0701
#define WB_AGC_FW_LNA_PD_AGC_ATTACK_MS        0x0702
#define WB_AGC_FW_LNA_PD_AGC_RELEASE_MS       0x0703
#define WB_AGC_FW_LNA_PD_THRESHOLD            0x0704
#define WB_AGC_FM_MIXER_PD_AGC_ATTACK_MS      0x0705
#define WB_AGC_FM_MIXER_PD_AGC_RELEASE_MS     0x0706
#define WB_AGC_FM_MIXER_PD_THRESHOLD          0x0707
#define WB_AGC_AM_LNA_PD_AGC_ATTACK_MS        0x070C
#define WB_AGC_AM_LNA_PD_AGC_RELEASE_MS       0x070D
#define WB_AGC_AM_LNA_PD_THRESHOLD            0x070E
#define WB_AGC_OVERRIDE                       0x0710
#define WB_AGC_FMATTEN1                       0x0711
#define WB_AGC_FMATTEN2                       0x0712
#define WB_AGC_LNA_GAIN                       0x0713
#define WB_AGC_PGA_GAIN                       0x0714
#define WB_AGC_WHIP_CAP_ATTEN                 0x0715
#define WB_AGC_WHIP_RES_ATTEN                 0x0716
#define WB_SEEK_BAND_BOTTOM                   0x1100
#define WB_SEEK_BAND_TOP                      0x1101
#define WB_SEEK_FREQUENCY_SPACING             0x1102
#define WB_RSQ_INTERRUPT_SOURCE               0x1200
#define WB_RSQ_SNR_HIGH_THRESHOLD             0x1201
#define WB_RSQ_SNR_LOW_THRESHOLD              0x1202
#define WB_RSQ_RSSI_HIGH_THRESHOLD            0x1203
#define WB_RSQ_RSSI_LOW_THRESHOLD             0x1204
#define WB_RSQ_ISSI_HIGH_THRESHOLD            0x1205
#define WB_RSQ_ISSI_LOW_THRESHOLD             0x1206
#define WB_ACF_INTERRUPT_SOURCE               0x1300
#define WB_ACF_SM_THRESHOLD                   0x1301
#define WB_ACF_CBW_THRESHOLD                  0x1302
#define WB_ACF_HC_THRESHOLD                   0x1303
#define WB_ACF_CONTROL_SOURCE                 0x1306
#define WB_VALID_MAX_TUNE_ERROR               0x2000
#define WB_VALID_RSSI_TIME                    0x2001
#define WB_VALID_SNR_TIME                     0x2002
#define WB_VALID_SNR_THRESHOLD                0x2003
#define WB_VALID_RSSI_THRESHOLD               0x2004
#define WB_VALID_ISSI_THRESHOLD               0x2005
#define WB_CHBW_SNR_MIN_MAX                   0x2200
#define WB_CHBW_SNR_HIGH_THRESHOLD            0x2201
#define WB_CHBW_SNR_LOW_THRESHOLD             0x2202
#define WB_CHBW_SNR_WIDENING_TIME             0x2203
#define WB_CHBW_SNR_NARROWING_TIME            0x2204
#define WB_CHBW_ASSI_MIN_MAX                  0x2205
#define WB_CHBW_ASSI_LOW_THRESHOLD            0x2206
#define WB_CHBW_ASSI_HIGH_THRESHOLD           0x2207
#define WB_CHBW_ASSI_WIDENING_TIME            0x2208
#define WB_CHBW_ASSI_NARROWING_TIME           0x2209
#define WB_HICUT_SNR_HIGH_THRESHOLD           0x3100
#define WB_HICUT_SNR_LOW_THRESHOLD            0x3101
#define WB_HICUT_ATTACK_TIME                  0x3106
#define WB_HICUT_RELEASE_TIME                 0x3107
#define WB_HICUT_CUTOFF_FREQ                  0x3108
#define WB_ASQ_INTERRUPT_SOURCE               0x5000
#define WB_ASQ_DETECT_RANGE                   0x5001
#define WB_ASQ_DETECT_THRESHOLD               0x5002

// WB Receive SAME Properties
#define WB_SAME_INTERRUPT_SOURCE              0x5100
#define WB_SAME_CONFIG                        0x5101

#endif
