#ifndef _SETTING_SQLITE_TABLE_H_
#define _SETTING_SQLITE_TABLE_H_

#include "SingleRowTable.h"
#include "TableNameDef.h"

using namespace std;

typedef enum
{
    VDR_PARA_HEART_BEAT_INTERVAL = 0,
    VDR_PARA_TCP_REPLY_TIMEOUT,
    VDR_PARA_TCP_RETRY_TIMES,
    VDR_PARA_UDP_REPLY_TIMEOUT,
    VDR_PARA_UDP_RETRY_TIMES,
    VDR_PARA_SMS_REPLY_TIMEOUT,
    VDR_PARA_SMS_RETRY_TIMES,
    VDR_PARA_MAIN_SERVER_APN,
    VDR_PARA_MAIN_SERVER_USERNAME,
    VDR_PARA_MAIN_SERVER_PASSWORD,
    VDR_PARA_MAIN_SERVER_ADDRESS,
    VDR_PARA_SECOND_SERVER_APN,
    VDR_PARA_SECOND_SERVER_USERNAME,
    VDR_PARA_SECOND_SERVER_PASSWORD,
    VDR_PARA_SECOND_SERVER_ADDRESS,
    VDR_PARA_TCP_PORT,
    VDR_PARA_UDP_PORT,
    VDR_PARA_LOC_REPORT_POLICY,
    VDR_PARA_LOC_REPORT_SCENARIO,
    VDR_PARA_NOLOGIN_REPORT_INTERVAL,
    VDR_PARA_SLEEP_REPORT_INTERVAL,
    VDR_PARA_EMERGENCY_REPORT_INTERVAL,
    VDR_PARA_DEFAULT_REPORT_INTERVAL,
    VDR_PARA_DEFAULT_REPORT_DISTANCE,
    VDR_PARA_NOLOGIN_REPORT_DISTANCE,
    VDR_PARA_SLEEP_REPORT_DISTANCE,
    VDR_PARA_EMERGENCY_REPORT_DISTANCE,
    VDR_PARA_TURN_ANGLE,
    VDR_PARA_PLATFORM_TEL,
    VDR_PARA_RESET_TEL,
    VDR_PARA_FACTORY_RESET_TEL,
    VDR_PARA_PLATFORM_SMS,
    VDR_PARA_REPORT_SMS,
    VDR_PARA_CALL_ANSWER_POLICY,
    VDR_PARA_CALL_DURATION_ONCE,
    VDR_PARA_CALL_DURATION_MONTH,
    VDR_PARA_MONITOR_TEL,
    VDR_PARA_MONITOR_SMS,
    VDR_PARA_WARNING_MASK,
    VDR_PARA_WARNING_SMS_MASK,
    VDR_PARA_WARNING_PHOTO_MASK,
    VDR_PARA_WARNING_PHOTOSAVE_MASK,
    VDR_PARA_WARNING_KEY_MASK,
    VDR_PARA_MAX_SPEED,
    VDR_PARA_OVERSPEED_DURATION,
    VDR_PARA_CONT_DRIVE_THRESHOLD,
    VDR_PARA_DAY_DRIVE_THRESHOLD,
    VDR_PARA_REST_MIN,
    VDR_PARA_PARKING_MAX,
    VDR_PARA_PHOTO_QUALITY,
    VDR_PARA_PHOTO_BRIGHTNESS,
    VDR_PARA_PHOTO_CONTRAST,
    VDR_PARA_PHOTO_SATUATION,
    VDR_PARA_PHOTO_CHROMA,
    VDR_PARA_FENCE_RADIUS,
    VDR_PARA_IC_MAIN_SERVER_IP_ADDR,
    VDR_PARA_IC_MAIN_SERVER_TCP_PORT,
    VDR_PARA_IC_MAIN_SERVER_UDP_PORT,
    VDR_PARA_IC_SECOND_SERVER_IP_ADDR,
    VDR_PARA_OVERSPEED_WARNING,
    VDR_PARA_TIRED_DRIVE_WARNING,
    VDR_PARA_COLLISION_ALARM,
    VDR_PARA_ROLLOVER_ALARM,
    VDR_PARA_TIME_CAPTURE_SET,
    VDR_PARA_DISTANCE_CAPTURE_SET,
    VDR_PARA_GNSS_LOC_MODE,
    VDR_PARA_GNSS_BAUD_RATE,
    VDR_PARA_GNSS_DATA_OUT_RATE,
    VDR_PARA_GNSS_DATA_COLLECT_RATE,
    VDR_PARA_GNSS_DATA_UPLOAD_MODE,
    VDR_PARA_GNSS_DATA_UPLOAD_SET,
    VDR_PARA_CAN_1_COLLECT_INTERVAL,
    VDR_PARA_CAN_1_UPLOAD_INTERVAL,
    VDR_PARA_CAN_2_COLLECT_INTERVAL,
    VDR_PARA_CAN_2_UPLOAD_INTERVAL,
    VDR_PARA_CAN_ID_COLLECT_SET,
    VDR_PARA_OTHER_CAN_ID_COLLECT_SET,
    VDR_PARA_BUTT
}ENUM_VDR_PARA_COL;

class VDRRunParaTable : public SingleRowTable
{
public:
    VDRRunParaTable();
};

typedef enum
{
        VDR_TEL,
        VDR_CHECK_BUTT,
}ENUM_VDR_OCCUPATION_STANDARD_CHECK_COL;

class VDROccupationCheckTable : public SingleRowTable
{
public:
        VDROccupationCheckTable();
};
#endif
