#ifndef DIDISPLAYLINE_H
#define DIDISPLAYLINE_H

#include <platform_types.h>

#ifdef __cplusplus
extern "C" {
#endif

/// @addtogroup Display
/// @{

/// @addtogroup UnUsed
/// @ingroup Display
/// @{

/// @addtogroup RoadLabelling
/// @ingroup UnUsed
/// @{

/// @addtogroup DisplayLine
/// @ingroup RoadLabelling

// This structure is used to store line segments that are generated by the
// display code.  Such segments are only stored if the name placement code
// returns a non NULL pointer from the display_addRoadName function.
typedef struct TDisplayLine
{
  // start of line coordinates (screen coordinates)
  INT16 x1,y1;
  // end of line coordinates (screen coordinates)
  INT16 x2,y2;
} TDisplayLine;

/// @}

/// @}

/// @}
#ifdef __cplusplus
}
#endif

#endif
