#ifndef DATAMANAGER_DEFINE_H
#define DATAMANAGER_DEFINE_H

#include <QString>
#include <QMetaType>  
#include "debugMonitor.h"


namespace DataManager
{

#define DATA_E_OK 								0
#define USERDATA_ERROR  						1
#define RUBAREA_UMOUNT 						2

#define DATA_E_NOT_INIT						-1

#define SERVICE_BACKNAME 			"/Service.db"

typedef enum  _USER_DATA_SURPOR_TYPE
{
	TYPE_FRIST = 0,
	TYPE_DATA_BASE ,
	TYPE_MEDIA_LIST ,
	TYPE_MAX
}USER_DATA_SURPOR_TYPE;
typedef enum  _DM_ERROR_INFO
{
	DM_E_OK = 0,
	DM_E_CHECK_VERSION_ERROR ,
	DM_E_DATA_BASE_ERROR,
	DM_E_LOAD_PLUGIN_ERROR,
	DM_E_ADDRESS_NO_EXIST ,
	DM_E_ADDRESS_READWRITE_ERROR,
	DM_E_ADDRESS_NOT_ENOUGH,
	DM_E_BACKUP_ERROR,
	DM_E_REVER_ERROR,
	DM_E_REPAIR_SUBAREA_START,
	DM_E_REPAIR_SUBAREA_OK,
	DM_E_REPAIR_SUBAREA_ERROR,
	DM_E_REPAIR_DATA_ERROR,
	DM_E_GET_VERSION_ERROR,
	DM_E_ERROR_MAX
	
}DM_ERROR_INFO;

}


#endif //IBMEDIA_DEFINE_H
